### ISSUE TITLE
Custom element doesn't exist: ztm_stop_card

### ISSUE THREAD

**Issue by QBANIN** [peetereczek/ztm-stop-card#4]
HA 0.115.6
HACS 1.6.0

Integration installed from HACS but it doesnt work:

```
Custom element doesn't exist: ztm_stop_card.
type: 'custom:ztm_stop_card'
```
Either path is wrong or some bug in integration because /www/community/ztm_stop_card/ztm_stop_card.js path doesn't exist after installation. There's /www/community/ztm-stop-card/ztm-stop-card.js insted but changing custom:ztm_stop_card to custom:ztm-stop-card in lovelace card doesn't work.

**Comment by QBANIN** [comment]
Uninstalled/installed again and now it works fine with **custom:ztm-stop-card**

**Comment by peetereczek** [comment]
My bad, I was fixing #3 

Installation with HACS works

**Comment by peetereczek** [comment]
Please check your Lovelace resources, if you have it configured correctly

![image](https://user-images.githubusercontent.com/42431204/96997643-70cd8f80-1532-11eb-9137-d959f828bc90.png)
