### ISSUE TITLE
Problem z konfiguracją karty

### ISSUE THREAD

**Issue by konradtomaszewski** [peetereczek/ztm-stop-card#6]
Przy konfiguracji karty mam w nagłówku komunikat: No card type configured
Niezbędne integracje zostały włączone

**Konfiguracja w configuration.yaml**
sensor:
  - platform: ztm
    api_key: XXX-XXX
    lines:
      - number: 17
        stop_id: 3286
        stop_number: "03"

**Konfiguracja karty w yaml:**
resources:
  - type: module
    url: /www/community/ztm-stop-card/ztm-stop-card.js
cards:
  - type: custom:ztm-stop-card
    entity: sensor.ztm_17_from_3286_03
  - type: custom:bkk-stop-card
    entity: sensor.ztm_17_from_3286_03

Proszę o podpowiedź co jest/może być problemem

**Comment by konradtomaszewski** [comment]
już znalazłem w czym był problem

**Comment by peetereczek** [comment]
Mógłbyś opisać co? Może powinienem zaktualizować dokumentację?

**Comment by ffgambler** [comment]
W Readme widnieje:
`custom:ztm_stop_card`
Zamiast podkreślników powinny być myślniki.
Drugi przykład zawiera też
`bkk-stop-card`
a powinno być 
`ztm-stop-card`
Jako początkujący nie bardzo wiedziałem też gdzie dodać resources- to akurat moja niewiedza ale czytelniej by było, gdyby umieścić to oddzielnie od definicji kart.

**Comment by peetereczek** [comment]
Przepraszam za te literówki, już poprawiłem
